# Generated by Django 4.2 on 2023-05-24 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coaching', '0001_initial'),
        ('libs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Кастомный приём пищи',
                'verbose_name_plural': 'Кастомные приёмы пищи',
            },
        ),
        migrations.CreateModel(
            name='DayNutrients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('water', models.FloatField()),
                ('proteins', models.FloatField()),
                ('fats', models.FloatField()),
                ('carbohydrates', models.FloatField()),
                ('calories', models.FloatField()),
            ],
            options={
                'verbose_name': 'Дневной калораж / БЖУ',
                'verbose_name_plural': 'Дневной калораж / БЖУ',
            },
        ),
        migrations.CreateModel(
            name='DietProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_start', models.DateField(null=True)),
                ('date_finish', models.DateField(null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaching.client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('forbidden_products', models.ManyToManyField(related_name='forbidden', to='libs.product')),
                ('recommended_products', models.ManyToManyField(related_name='recommended', to='libs.product')),
            ],
            options={
                'verbose_name': 'Диета',
                'verbose_name_plural': 'Диета',
            },
        ),
        migrations.CreateModel(
            name='DietProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('diet_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_reference', to='diet.dietprogram')),
            ],
            options={
                'verbose_name': 'Рацион на день',
                'verbose_name_plural': 'Рационы на день',
            },
        ),
        migrations.CreateModel(
            name='SupplementAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milligrams', models.FloatField(default=1000.0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libs.supplement')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.dietprogram')),
            ],
            options={
                'verbose_name': 'Запись о количестве БАДа',
                'verbose_name_plural': 'Записи о количестве БАДов',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='diet.dietprogramday')),
            ],
            options={
                'verbose_name': 'Приём пищи',
                'verbose_name_plural': 'Приёмы пищи',
            },
        ),
        migrations.CreateModel(
            name='FoodAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.FloatField(default=100.0)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foodamount', to='diet.meal')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libs.product')),
            ],
            options={
                'verbose_name': 'Запись о количестве продукта',
                'verbose_name_plural': 'Записи о количестве продуктов',
            },
        ),
        migrations.CreateModel(
            name='DietSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('day_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.daynutrients')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='diet.dietprogram')),
            ],
            options={
                'verbose_name': 'Дни цикла диеты',
                'verbose_name_plural': 'Дни циклов диеты',
            },
        ),
        migrations.AddField(
            model_name='daynutrients',
            name='diet_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='diet.dietprogram'),
        ),
        migrations.CreateModel(
            name='CustomMealFoodAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.FloatField(default=100.0)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diet.custommeal')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libs.product')),
            ],
            options={
                'verbose_name': 'Запись о количестве продукта',
                'verbose_name_plural': 'Записи о количестве продуктов',
            },
        ),
    ]
