version: '3'

services:
  django:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn prod.wsgi:application --bind 0.0.0.0:8000 -k gevent
    expose:
      - 8000
    env_file:
      - ./.env.prod
    volumes:
      - staticfiles:/home/app/django/static
      - mediafiles:/home/app/django/media
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx      
    ports:
      - 1337:80
    volumes:
      - staticfiles:/home/app/django/static
      - mediafiles:/home/app/django/media
    depends_on:
      - django

volumes:
  postgres_data:
  staticfiles:
  mediafiles: