# Generated by Django 4.2 on 2023-06-02 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('gender', models.CharField(choices=[('M', 'Man'), ('W', 'Woman')], max_length=1)),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sport', models.ManyToManyField(blank=True, to='libs.sport')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='ClientStatsActive',
            fields=[
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bodyfat_percent', models.FloatField(blank=True, null=True)),
                ('neck', models.FloatField(blank=True, null=True)),
                ('shoulders', models.FloatField(blank=True, null=True)),
                ('chest', models.FloatField(blank=True, null=True)),
                ('bicep', models.FloatField(blank=True, null=True)),
                ('forearm', models.FloatField(blank=True, null=True)),
                ('waist', models.FloatField(blank=True, null=True)),
                ('glutes', models.FloatField(blank=True, null=True)),
                ('legs', models.FloatField(blank=True, null=True)),
                ('calves', models.FloatField(blank=True, null=True)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='coaching.client')),
                ('date_update', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Статистика клиента',
                'verbose_name_plural': 'Статистика клиентов',
            },
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Новая программа', max_length=127)),
                ('description', models.TextField()),
                ('time_start', models.DateField()),
                ('time_finish', models.DateField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaching.client')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Программа тренировок',
                'verbose_name_plural': 'Программы тренировок',
            },
        ),
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='coaching.trainingprogram')),
            ],
            options={
                'verbose_name': 'Тренироваочный день',
                'verbose_name_plural': 'Тренировочные дни',
            },
        ),
        migrations.CreateModel(
            name='ExerciseAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True)),
                ('count', models.IntegerField()),
                ('reps', models.IntegerField(null=True)),
                ('sets', models.IntegerField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('comment', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='libs.exercise')),
                ('training_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examount', to='coaching.trainingday')),
            ],
            options={
                'verbose_name': 'Запись об упражнениях',
                'verbose_name_plural': 'Записи об упражнениях',
            },
        ),
        migrations.CreateModel(
            name='ClientStatsArchieved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('bodyfat_percent', models.FloatField(blank=True, null=True)),
                ('neck', models.FloatField(blank=True, null=True)),
                ('shoulders', models.FloatField(blank=True, null=True)),
                ('chest', models.FloatField(blank=True, null=True)),
                ('bicep', models.FloatField(blank=True, null=True)),
                ('forearm', models.FloatField(blank=True, null=True)),
                ('waist', models.FloatField(blank=True, null=True)),
                ('glutes', models.FloatField(blank=True, null=True)),
                ('legs', models.FloatField(blank=True, null=True)),
                ('calves', models.FloatField(blank=True, null=True)),
                ('date_created', models.DateField()),
                ('date_archieved', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coaching.client')),
            ],
            options={
                'verbose_name': 'Архивная статистика клиента',
                'verbose_name_plural': 'Архивная статистика клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientBaseExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='coaching.client')),
                ('exercises', models.ManyToManyField(to='libs.exercise')),
            ],
            options={
                'verbose_name': 'Упражнения для отслеживания статистики',
                'verbose_name_plural': 'Упражнения для отслеживания статистики',
            },
        ),
    ]
