# Generated by Django 4.2 on 2023-05-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientstatsarchieved',
            name='date_update',
        ),
    ]
