# Generated by Django 4.2 on 2023-05-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libs', '0001_initial'),
        ('coaching', '0002_remove_clientstatsarchieved_date_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sport',
            field=models.ManyToManyField(blank=True, to='libs.sport'),
        ),
    ]
