# Generated by Django 4.2 on 2023-05-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cabinet', '0001_initial'),
        ('libs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecard',
            name='sport',
            field=models.ManyToManyField(blank=True, to='libs.sport'),
        ),
    ]
