# Generated by Django 4.2 on 2023-05-25 08:15

import cabinet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.ImageField(null=True, upload_to=cabinet.models.path_post_pic),
        ),
    ]
